module.exports = { 
  tweets: [ { created_at: 'Sat Aug 06 00:08:36 +0000 2016',
    id: 761715560904167400,
    id_str: '761715560904167424',
    text: 'We\'re keeping it cool on this sunny Southern California #fridaypieday with our Sunnylicious Lemon Cream Cheese!  https://t.co/nQfJ3FPDaI',
    truncated: false,
    entities: 
     { hashtags: [Object],
       symbols: [],
       user_mentions: [],
       urls: [Object] },
    source: '<a href="http://momentfeed.com" rel="nofollow">MomentFeed.</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: 
     { id: 77289038,
       id_str: '77289038',
       name: 'Polly\'s Pies',
       screen_name: 'Pollyspiescafe',
       location: 'Southern California',
       description: 'Polly\'s Pies offers excellent service, the freshest, tastiest homestyle cooking and baking - all at very reasonable prices!',
       url: 'http://t.co/CDVl5Cd0aN',
       entities: [Object],
       protected: false,
       followers_count: 1425,
       friends_count: 912,
       listed_count: 48,
       created_at: 'Fri Sep 25 19:22:11 +0000 2009',
       favourites_count: 327,
       utc_offset: -25200,
       time_zone: 'Pacific Time (US & Canada)',
       geo_enabled: true,
       verified: false,
       statuses_count: 1179,
       lang: 'en',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'BA68AE',
       profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/456584854126071808/eA4uCNEE.jpeg',
       profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/456584854126071808/eA4uCNEE.jpeg',
       profile_background_tile: true,
       profile_image_url: 'http://pbs.twimg.com/profile_images/761714490681417729/kjI3GIcB_normal.jpg',
       profile_image_url_https: 'https://pbs.twimg.com/profile_images/761714490681417729/kjI3GIcB_normal.jpg',
       profile_banner_url: 'https://pbs.twimg.com/profile_banners/77289038/1467135216',
       profile_link_color: '7FDBB6',
       profile_sidebar_border_color: 'FFFFFF',
       profile_sidebar_fill_color: 'DDFFCC',
       profile_text_color: '333333',
       profile_use_background_image: true,
       has_extended_profile: false,
       default_profile: false,
       default_profile_image: false,
       following: true,
       follow_request_sent: false,
       notifications: false },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    lang: 'en' },
  { created_at: 'Mon Jul 25 20:11:48 +0000 2016',
    id: 757669704353718300,
    id_str: '757669704353718272',
    text: '@DonaldGarner5 You should try our Banberry Pie Shake! Also pink and SO delicious!',
    truncated: false,
    entities: { hashtags: [], symbols: [], user_mentions: [Object], urls: [] },
    source: '<a href="http://momentfeed.com" rel="nofollow">MomentFeed.</a>',
    in_reply_to_status_id: 757463331431075800,
    in_reply_to_status_id_str: '757463331431075840',
    in_reply_to_user_id: 553089389,
    in_reply_to_user_id_str: '553089389',
    in_reply_to_screen_name: 'DonaldGarner5',
    user: 
     { id: 77289038,
       id_str: '77289038',
       name: 'Polly\'s Pies',
       screen_name: 'Pollyspiescafe',
       location: 'Southern California',
       description: 'Polly\'s Pies offers excellent service, the freshest, tastiest homestyle cooking and baking - all at very reasonable prices!',
       url: 'http://t.co/CDVl5Cd0aN',
       entities: [Object],
       protected: false,
       followers_count: 1425,
       friends_count: 912,
       listed_count: 48,
       created_at: 'Fri Sep 25 19:22:11 +0000 2009',
       favourites_count: 327,
       utc_offset: -25200,
       time_zone: 'Pacific Time (US & Canada)',
       geo_enabled: true,
       verified: false,
       statuses_count: 1179,
       lang: 'en',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'BA68AE',
       profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/456584854126071808/eA4uCNEE.jpeg',
       profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/456584854126071808/eA4uCNEE.jpeg',
       profile_background_tile: true,
       profile_image_url: 'http://pbs.twimg.com/profile_images/761714490681417729/kjI3GIcB_normal.jpg',
       profile_image_url_https: 'https://pbs.twimg.com/profile_images/761714490681417729/kjI3GIcB_normal.jpg',
       profile_banner_url: 'https://pbs.twimg.com/profile_banners/77289038/1467135216',
       profile_link_color: '7FDBB6',
       profile_sidebar_border_color: 'FFFFFF',
       profile_sidebar_fill_color: 'DDFFCC',
       profile_text_color: '333333',
       profile_use_background_image: true,
       has_extended_profile: false,
       default_profile: false,
       default_profile_image: false,
       following: true,
       follow_request_sent: false,
       notifications: false },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 1,
    favorited: false,
    retweeted: false,
    lang: 'en' },
  { created_at: 'Fri Jul 22 23:35:48 +0000 2016',
    id: 756633879029481500,
    id_str: '756633879029481472',
    text: 'Get an EXTRA $1 off our Fresh Fruit and sale pies now through Monday by mentioning our secret word: POLLY\'S PERKS! https://t.co/Pf8P7XdAlS',
    truncated: false,
    entities: { hashtags: [], symbols: [], user_mentions: [], urls: [Object] },
    source: '<a href="http://momentfeed.com" rel="nofollow">MomentFeed.</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: 
     { id: 77289038,
       id_str: '77289038',
       name: 'Polly\'s Pies',
       screen_name: 'Pollyspiescafe',
       location: 'Southern California',
       description: 'Polly\'s Pies offers excellent service, the freshest, tastiest homestyle cooking and baking - all at very reasonable prices!',
       url: 'http://t.co/CDVl5Cd0aN',
       entities: [Object],
       protected: false,
       followers_count: 1425,
       friends_count: 912,
       listed_count: 48,
       created_at: 'Fri Sep 25 19:22:11 +0000 2009',
       favourites_count: 327,
       utc_offset: -25200,
       time_zone: 'Pacific Time (US & Canada)',
       geo_enabled: true,
       verified: false,
       statuses_count: 1179,
       lang: 'en',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'BA68AE',
       profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/456584854126071808/eA4uCNEE.jpeg',
       profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/456584854126071808/eA4uCNEE.jpeg',
       profile_background_tile: true,
       profile_image_url: 'http://pbs.twimg.com/profile_images/761714490681417729/kjI3GIcB_normal.jpg',
       profile_image_url_https: 'https://pbs.twimg.com/profile_images/761714490681417729/kjI3GIcB_normal.jpg',
       profile_banner_url: 'https://pbs.twimg.com/profile_banners/77289038/1467135216',
       profile_link_color: '7FDBB6',
       profile_sidebar_border_color: 'FFFFFF',
       profile_sidebar_fill_color: 'DDFFCC',
       profile_text_color: '333333',
       profile_use_background_image: true,
       has_extended_profile: false,
       default_profile: false,
       default_profile_image: false,
       following: true,
       follow_request_sent: false,
       notifications: false },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    lang: 'en' },
  { created_at: 'Thu Jul 21 18:04:49 +0000 2016',
    id: 756188192559108100,
    id_str: '756188192559108096',
    text: 'Have you tried our Burger &amp; Pie shake promo yet? Pictured here is our Sourdough Burger taken by Polly\'s Fan @reiluv https://t.co/jJXylYQien',
    truncated: false,
    entities: 
     { hashtags: [],
       symbols: [],
       user_mentions: [Object],
       urls: [Object] },
    source: '<a href="http://momentfeed.com" rel="nofollow">MomentFeed.</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: 
     { id: 77289038,
       id_str: '77289038',
       name: 'Polly\'s Pies',
       screen_name: 'Pollyspiescafe',
       location: 'Southern California',
       description: 'Polly\'s Pies offers excellent service, the freshest, tastiest homestyle cooking and baking - all at very reasonable prices!',
       url: 'http://t.co/CDVl5Cd0aN',
       entities: [Object],
       protected: false,
       followers_count: 1425,
       friends_count: 912,
       listed_count: 48,
       created_at: 'Fri Sep 25 19:22:11 +0000 2009',
       favourites_count: 327,
       utc_offset: -25200,
       time_zone: 'Pacific Time (US & Canada)',
       geo_enabled: true,
       verified: false,
       statuses_count: 1179,
       lang: 'en',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'BA68AE',
       profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/456584854126071808/eA4uCNEE.jpeg',
       profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/456584854126071808/eA4uCNEE.jpeg',
       profile_background_tile: true,
       profile_image_url: 'http://pbs.twimg.com/profile_images/761714490681417729/kjI3GIcB_normal.jpg',
       profile_image_url_https: 'https://pbs.twimg.com/profile_images/761714490681417729/kjI3GIcB_normal.jpg',
       profile_banner_url: 'https://pbs.twimg.com/profile_banners/77289038/1467135216',
       profile_link_color: '7FDBB6',
       profile_sidebar_border_color: 'FFFFFF',
       profile_sidebar_fill_color: 'DDFFCC',
       profile_text_color: '333333',
       profile_use_background_image: true,
       has_extended_profile: false,
       default_profile: false,
       default_profile_image: false,
       following: true,
       follow_request_sent: false,
       notifications: false },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 1,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    lang: 'en' },
  { created_at: 'Thu Jul 21 16:35:18 +0000 2016',
    id: 756165666718101500,
    id_str: '756165666718101505',
    text: 'RT @DisneySportsGuy: Cinnamon French Toast from @Pollyspiescafe! #soyummy https://t.co/zsqN6EEwF7',
    truncated: false,
    entities: 
     { hashtags: [Object],
       symbols: [],
       user_mentions: [Object],
       urls: [],
       media: [Object] },
    extended_entities: { media: [Object] },
    source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: 
     { id: 77289038,
       id_str: '77289038',
       name: 'Polly\'s Pies',
       screen_name: 'Pollyspiescafe',
       location: 'Southern California',
       description: 'Polly\'s Pies offers excellent service, the freshest, tastiest homestyle cooking and baking - all at very reasonable prices!',
       url: 'http://t.co/CDVl5Cd0aN',
       entities: [Object],
       protected: false,
       followers_count: 1425,
       friends_count: 912,
       listed_count: 48,
       created_at: 'Fri Sep 25 19:22:11 +0000 2009',
       favourites_count: 327,
       utc_offset: -25200,
       time_zone: 'Pacific Time (US & Canada)',
       geo_enabled: true,
       verified: false,
       statuses_count: 1179,
       lang: 'en',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'BA68AE',
       profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/456584854126071808/eA4uCNEE.jpeg',
       profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/456584854126071808/eA4uCNEE.jpeg',
       profile_background_tile: true,
       profile_image_url: 'http://pbs.twimg.com/profile_images/761714490681417729/kjI3GIcB_normal.jpg',
       profile_image_url_https: 'https://pbs.twimg.com/profile_images/761714490681417729/kjI3GIcB_normal.jpg',
       profile_banner_url: 'https://pbs.twimg.com/profile_banners/77289038/1467135216',
       profile_link_color: '7FDBB6',
       profile_sidebar_border_color: 'FFFFFF',
       profile_sidebar_fill_color: 'DDFFCC',
       profile_text_color: '333333',
       profile_use_background_image: true,
       has_extended_profile: false,
       default_profile: false,
       default_profile_image: false,
       following: true,
       follow_request_sent: false,
       notifications: false },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    retweeted_status: 
     { created_at: 'Sat Jul 16 18:19:41 +0000 2016',
       id: 754379995116507100,
       id_str: '754379995116507138',
       text: 'Cinnamon French Toast from @Pollyspiescafe! #soyummy https://t.co/zsqN6EEwF7',
       truncated: false,
       entities: [Object],
       extended_entities: [Object],
       source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       is_quote_status: false,
       retweet_count: 1,
       favorite_count: 0,
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       lang: 'en' },
    is_quote_status: false,
    retweet_count: 1,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    lang: 'en' },
  { created_at: 'Thu Jul 14 00:02:00 +0000 2016',
    id: 753378978052747300,
    id_str: '753378978052747264',
    text: 'Our new pie boxes are in! You now have an excuse to drop by and pick up a pie. You\'re welcome!  https://t.co/TS6ZJu3R0t',
    truncated: false,
    entities: { hashtags: [], symbols: [], user_mentions: [], urls: [Object] },
    source: '<a href="http://momentfeed.com" rel="nofollow">MomentFeed.</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: 
     { id: 77289038,
       id_str: '77289038',
       name: 'Polly\'s Pies',
       screen_name: 'Pollyspiescafe',
       location: 'Southern California',
       description: 'Polly\'s Pies offers excellent service, the freshest, tastiest homestyle cooking and baking - all at very reasonable prices!',
       url: 'http://t.co/CDVl5Cd0aN',
       entities: [Object],
       protected: false,
       followers_count: 1425,
       friends_count: 912,
       listed_count: 48,
       created_at: 'Fri Sep 25 19:22:11 +0000 2009',
       favourites_count: 327,
       utc_offset: -25200,
       time_zone: 'Pacific Time (US & Canada)',
       geo_enabled: true,
       verified: false,
       statuses_count: 1179,
       lang: 'en',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'BA68AE',
       profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/456584854126071808/eA4uCNEE.jpeg',
       profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/456584854126071808/eA4uCNEE.jpeg',
       profile_background_tile: true,
       profile_image_url: 'http://pbs.twimg.com/profile_images/761714490681417729/kjI3GIcB_normal.jpg',
       profile_image_url_https: 'https://pbs.twimg.com/profile_images/761714490681417729/kjI3GIcB_normal.jpg',
       profile_banner_url: 'https://pbs.twimg.com/profile_banners/77289038/1467135216',
       profile_link_color: '7FDBB6',
       profile_sidebar_border_color: 'FFFFFF',
       profile_sidebar_fill_color: 'DDFFCC',
       profile_text_color: '333333',
       profile_use_background_image: true,
       has_extended_profile: false,
       default_profile: false,
       default_profile_image: false,
       following: true,
       follow_request_sent: false,
       notifications: false },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    lang: 'en' },
  { created_at: 'Wed Jul 13 00:02:00 +0000 2016',
    id: 753016589780340700,
    id_str: '753016589780340737',
    text: 'We\'re hiring! Join the Polly\'s team today: https://t.co/xJsmKCrpbN',
    truncated: false,
    entities: { hashtags: [], symbols: [], user_mentions: [], urls: [Object] },
    source: '<a href="http://momentfeed.com" rel="nofollow">MomentFeed.</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: 
     { id: 77289038,
       id_str: '77289038',
       name: 'Polly\'s Pies',
       screen_name: 'Pollyspiescafe',
       location: 'Southern California',
       description: 'Polly\'s Pies offers excellent service, the freshest, tastiest homestyle cooking and baking - all at very reasonable prices!',
       url: 'http://t.co/CDVl5Cd0aN',
       entities: [Object],
       protected: false,
       followers_count: 1425,
       friends_count: 912,
       listed_count: 48,
       created_at: 'Fri Sep 25 19:22:11 +0000 2009',
       favourites_count: 327,
       utc_offset: -25200,
       time_zone: 'Pacific Time (US & Canada)',
       geo_enabled: true,
       verified: false,
       statuses_count: 1179,
       lang: 'en',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'BA68AE',
       profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/456584854126071808/eA4uCNEE.jpeg',
       profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/456584854126071808/eA4uCNEE.jpeg',
       profile_background_tile: true,
       profile_image_url: 'http://pbs.twimg.com/profile_images/761714490681417729/kjI3GIcB_normal.jpg',
       profile_image_url_https: 'https://pbs.twimg.com/profile_images/761714490681417729/kjI3GIcB_normal.jpg',
       profile_banner_url: 'https://pbs.twimg.com/profile_banners/77289038/1467135216',
       profile_link_color: '7FDBB6',
       profile_sidebar_border_color: 'FFFFFF',
       profile_sidebar_fill_color: 'DDFFCC',
       profile_text_color: '333333',
       profile_use_background_image: true,
       has_extended_profile: false,
       default_profile: false,
       default_profile_image: false,
       following: true,
       follow_request_sent: false,
       notifications: false },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    lang: 'en' },
  { created_at: 'Tue Jul 12 22:04:53 +0000 2016',
    id: 752987119388196900,
    id_str: '752987119388196864',
    text: 'RT @RociooKinss: All I want in life is a banberry pie from Polly\'s Pies',
    truncated: false,
    entities: { hashtags: [], symbols: [], user_mentions: [Object], urls: [] },
    source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: 
     { id: 77289038,
       id_str: '77289038',
       name: 'Polly\'s Pies',
       screen_name: 'Pollyspiescafe',
       location: 'Southern California',
       description: 'Polly\'s Pies offers excellent service, the freshest, tastiest homestyle cooking and baking - all at very reasonable prices!',
       url: 'http://t.co/CDVl5Cd0aN',
       entities: [Object],
       protected: false,
       followers_count: 1425,
       friends_count: 912,
       listed_count: 48,
       created_at: 'Fri Sep 25 19:22:11 +0000 2009',
       favourites_count: 327,
       utc_offset: -25200,
       time_zone: 'Pacific Time (US & Canada)',
       geo_enabled: true,
       verified: false,
       statuses_count: 1179,
       lang: 'en',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'BA68AE',
       profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/456584854126071808/eA4uCNEE.jpeg',
       profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/456584854126071808/eA4uCNEE.jpeg',
       profile_background_tile: true,
       profile_image_url: 'http://pbs.twimg.com/profile_images/761714490681417729/kjI3GIcB_normal.jpg',
       profile_image_url_https: 'https://pbs.twimg.com/profile_images/761714490681417729/kjI3GIcB_normal.jpg',
       profile_banner_url: 'https://pbs.twimg.com/profile_banners/77289038/1467135216',
       profile_link_color: '7FDBB6',
       profile_sidebar_border_color: 'FFFFFF',
       profile_sidebar_fill_color: 'DDFFCC',
       profile_text_color: '333333',
       profile_use_background_image: true,
       has_extended_profile: false,
       default_profile: false,
       default_profile_image: false,
       following: true,
       follow_request_sent: false,
       notifications: false },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    retweeted_status: 
     { created_at: 'Mon Jul 11 05:49:49 +0000 2016',
       id: 752379345893625900,
       id_str: '752379345893625856',
       text: 'All I want in life is a banberry pie from Polly\'s Pies',
       truncated: false,
       entities: [Object],
       source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       is_quote_status: false,
       retweet_count: 1,
       favorite_count: 0,
       favorited: false,
       retweeted: false,
       lang: 'en' },
    is_quote_status: false,
    retweet_count: 1,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: 'en' },
  { created_at: 'Tue Jul 12 16:35:17 +0000 2016',
    id: 752904171406241800,
    id_str: '752904171406241792',
    text: 'Introducing Polly\'s Hawaiian Macadamia Nut Coffee! Enjoy a cup in the dining room or take home a 1 lb. bag for 11.99 https://t.co/gAtcCEEVXA',
    truncated: false,
    entities: { hashtags: [], symbols: [], user_mentions: [], urls: [Object] },
    source: '<a href="http://momentfeed.com" rel="nofollow">MomentFeed.</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: 
     { id: 77289038,
       id_str: '77289038',
       name: 'Polly\'s Pies',
       screen_name: 'Pollyspiescafe',
       location: 'Southern California',
       description: 'Polly\'s Pies offers excellent service, the freshest, tastiest homestyle cooking and baking - all at very reasonable prices!',
       url: 'http://t.co/CDVl5Cd0aN',
       entities: [Object],
       protected: false,
       followers_count: 1425,
       friends_count: 912,
       listed_count: 48,
       created_at: 'Fri Sep 25 19:22:11 +0000 2009',
       favourites_count: 327,
       utc_offset: -25200,
       time_zone: 'Pacific Time (US & Canada)',
       geo_enabled: true,
       verified: false,
       statuses_count: 1179,
       lang: 'en',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'BA68AE',
       profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/456584854126071808/eA4uCNEE.jpeg',
       profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/456584854126071808/eA4uCNEE.jpeg',
       profile_background_tile: true,
       profile_image_url: 'http://pbs.twimg.com/profile_images/761714490681417729/kjI3GIcB_normal.jpg',
       profile_image_url_https: 'https://pbs.twimg.com/profile_images/761714490681417729/kjI3GIcB_normal.jpg',
       profile_banner_url: 'https://pbs.twimg.com/profile_banners/77289038/1467135216',
       profile_link_color: '7FDBB6',
       profile_sidebar_border_color: 'FFFFFF',
       profile_sidebar_fill_color: 'DDFFCC',
       profile_text_color: '333333',
       profile_use_background_image: true,
       has_extended_profile: false,
       default_profile: false,
       default_profile_image: false,
       following: true,
       follow_request_sent: false,
       notifications: false },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    lang: 'en' },
  { created_at: 'Tue Jul 12 00:20:11 +0000 2016',
    id: 752658780438028300,
    id_str: '752658780438028289',
    text: 'Meet our newest addition to Polly\'s Gourmet Coffee Line-Hawaiian Macadamia Nut! 🌴🌺☕️ #pollyspies… https://t.co/gAtcCEnl62',
    truncated: false,
    entities: 
     { hashtags: [Object],
       symbols: [],
       user_mentions: [],
       urls: [Object] },
    source: '<a href="http://instagram.com" rel="nofollow">Instagram</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: 
     { id: 77289038,
       id_str: '77289038',
       name: 'Polly\'s Pies',
       screen_name: 'Pollyspiescafe',
       location: 'Southern California',
       description: 'Polly\'s Pies offers excellent service, the freshest, tastiest homestyle cooking and baking - all at very reasonable prices!',
       url: 'http://t.co/CDVl5Cd0aN',
       entities: [Object],
       protected: false,
       followers_count: 1425,
       friends_count: 912,
       listed_count: 48,
       created_at: 'Fri Sep 25 19:22:11 +0000 2009',
       favourites_count: 327,
       utc_offset: -25200,
       time_zone: 'Pacific Time (US & Canada)',
       geo_enabled: true,
       verified: false,
       statuses_count: 1179,
       lang: 'en',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'BA68AE',
       profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/456584854126071808/eA4uCNEE.jpeg',
       profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/456584854126071808/eA4uCNEE.jpeg',
       profile_background_tile: true,
       profile_image_url: 'http://pbs.twimg.com/profile_images/761714490681417729/kjI3GIcB_normal.jpg',
       profile_image_url_https: 'https://pbs.twimg.com/profile_images/761714490681417729/kjI3GIcB_normal.jpg',
       profile_banner_url: 'https://pbs.twimg.com/profile_banners/77289038/1467135216',
       profile_link_color: '7FDBB6',
       profile_sidebar_border_color: 'FFFFFF',
       profile_sidebar_fill_color: 'DDFFCC',
       profile_text_color: '333333',
       profile_use_background_image: true,
       has_extended_profile: false,
       default_profile: false,
       default_profile_image: false,
       following: true,
       follow_request_sent: false,
       notifications: false },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 1,
    favorite_count: 2,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    lang: 'en' },
  { created_at: 'Sat Jul 09 00:31:00 +0000 2016',
    id: 751574337258332200,
    id_str: '751574337258332160',
    text: 'Our featured pie for #fridaypieday is our Chocolate Banberry! Here until August 8. Try it in a Pie Shake!  https://t.co/oMBxCOa4JV',
    truncated: false,
    entities: 
     { hashtags: [Object],
       symbols: [],
       user_mentions: [],
       urls: [Object] },
    source: '<a href="http://momentfeed.com" rel="nofollow">MomentFeed.</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: 
     { id: 77289038,
       id_str: '77289038',
       name: 'Polly\'s Pies',
       screen_name: 'Pollyspiescafe',
       location: 'Southern California',
       description: 'Polly\'s Pies offers excellent service, the freshest, tastiest homestyle cooking and baking - all at very reasonable prices!',
       url: 'http://t.co/CDVl5Cd0aN',
       entities: [Object],
       protected: false,
       followers_count: 1425,
       friends_count: 912,
       listed_count: 48,
       created_at: 'Fri Sep 25 19:22:11 +0000 2009',
       favourites_count: 327,
       utc_offset: -25200,
       time_zone: 'Pacific Time (US & Canada)',
       geo_enabled: true,
       verified: false,
       statuses_count: 1179,
       lang: 'en',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'BA68AE',
       profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/456584854126071808/eA4uCNEE.jpeg',
       profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/456584854126071808/eA4uCNEE.jpeg',
       profile_background_tile: true,
       profile_image_url: 'http://pbs.twimg.com/profile_images/761714490681417729/kjI3GIcB_normal.jpg',
       profile_image_url_https: 'https://pbs.twimg.com/profile_images/761714490681417729/kjI3GIcB_normal.jpg',
       profile_banner_url: 'https://pbs.twimg.com/profile_banners/77289038/1467135216',
       profile_link_color: '7FDBB6',
       profile_sidebar_border_color: 'FFFFFF',
       profile_sidebar_fill_color: 'DDFFCC',
       profile_text_color: '333333',
       profile_use_background_image: true,
       has_extended_profile: false,
       default_profile: false,
       default_profile_image: false,
       following: true,
       follow_request_sent: false,
       notifications: false },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    lang: 'en' },
  { created_at: 'Wed Jul 06 23:49:00 +0000 2016',
    id: 750838991826538500,
    id_str: '750838991826538496',
    text: '@TurtlyAriana That is a tragedy. We think he owes you an entire Apple Pie!',
    truncated: false,
    entities: { hashtags: [], symbols: [], user_mentions: [Object], urls: [] },
    source: '<a href="http://momentfeed.com" rel="nofollow">MomentFeed.</a>',
    in_reply_to_status_id: 749896440399351800,
    in_reply_to_status_id_str: '749896440399351808',
    in_reply_to_user_id: 3259421900,
    in_reply_to_user_id_str: '3259421900',
    in_reply_to_screen_name: 'TurtlyAriana',
    user: 
     { id: 77289038,
       id_str: '77289038',
       name: 'Polly\'s Pies',
       screen_name: 'Pollyspiescafe',
       location: 'Southern California',
       description: 'Polly\'s Pies offers excellent service, the freshest, tastiest homestyle cooking and baking - all at very reasonable prices!',
       url: 'http://t.co/CDVl5Cd0aN',
       entities: [Object],
       protected: false,
       followers_count: 1425,
       friends_count: 912,
       listed_count: 48,
       created_at: 'Fri Sep 25 19:22:11 +0000 2009',
       favourites_count: 327,
       utc_offset: -25200,
       time_zone: 'Pacific Time (US & Canada)',
       geo_enabled: true,
       verified: false,
       statuses_count: 1179,
       lang: 'en',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'BA68AE',
       profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/456584854126071808/eA4uCNEE.jpeg',
       profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/456584854126071808/eA4uCNEE.jpeg',
       profile_background_tile: true,
       profile_image_url: 'http://pbs.twimg.com/profile_images/761714490681417729/kjI3GIcB_normal.jpg',
       profile_image_url_https: 'https://pbs.twimg.com/profile_images/761714490681417729/kjI3GIcB_normal.jpg',
       profile_banner_url: 'https://pbs.twimg.com/profile_banners/77289038/1467135216',
       profile_link_color: '7FDBB6',
       profile_sidebar_border_color: 'FFFFFF',
       profile_sidebar_fill_color: 'DDFFCC',
       profile_text_color: '333333',
       profile_use_background_image: true,
       has_extended_profile: false,
       default_profile: false,
       default_profile_image: false,
       following: true,
       follow_request_sent: false,
       notifications: false },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: 'en' },
  { created_at: 'Wed Jul 06 23:35:00 +0000 2016',
    id: 750835468724383700,
    id_str: '750835468724383744',
    text: 'Chocolate Banberry Pie Shake to-go! https://t.co/6IKyHDgRQL',
    truncated: false,
    entities: { hashtags: [], symbols: [], user_mentions: [], urls: [Object] },
    source: '<a href="http://momentfeed.com" rel="nofollow">MomentFeed.</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: 
     { id: 77289038,
       id_str: '77289038',
       name: 'Polly\'s Pies',
       screen_name: 'Pollyspiescafe',
       location: 'Southern California',
       description: 'Polly\'s Pies offers excellent service, the freshest, tastiest homestyle cooking and baking - all at very reasonable prices!',
       url: 'http://t.co/CDVl5Cd0aN',
       entities: [Object],
       protected: false,
       followers_count: 1425,
       friends_count: 912,
       listed_count: 48,
       created_at: 'Fri Sep 25 19:22:11 +0000 2009',
       favourites_count: 327,
       utc_offset: -25200,
       time_zone: 'Pacific Time (US & Canada)',
       geo_enabled: true,
       verified: false,
       statuses_count: 1179,
       lang: 'en',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'BA68AE',
       profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/456584854126071808/eA4uCNEE.jpeg',
       profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/456584854126071808/eA4uCNEE.jpeg',
       profile_background_tile: true,
       profile_image_url: 'http://pbs.twimg.com/profile_images/761714490681417729/kjI3GIcB_normal.jpg',
       profile_image_url_https: 'https://pbs.twimg.com/profile_images/761714490681417729/kjI3GIcB_normal.jpg',
       profile_banner_url: 'https://pbs.twimg.com/profile_banners/77289038/1467135216',
       profile_link_color: '7FDBB6',
       profile_sidebar_border_color: 'FFFFFF',
       profile_sidebar_fill_color: 'DDFFCC',
       profile_text_color: '333333',
       profile_use_background_image: true,
       has_extended_profile: false,
       default_profile: false,
       default_profile_image: false,
       following: true,
       follow_request_sent: false,
       notifications: false },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    lang: 'en' },
  { created_at: 'Wed Jun 29 23:50:10 +0000 2016',
    id: 748302570980929500,
    id_str: '748302570980929537',
    text: 'Be sure to snap a picture of your Pie Shake and hashtag #pollyspieshakes to enter to win a $100 Polly\'s gift card! https://t.co/IFIcxZB3WG',
    truncated: false,
    entities: 
     { hashtags: [Object],
       symbols: [],
       user_mentions: [],
       urls: [Object] },
    source: '<a href="http://momentfeed.com" rel="nofollow">MomentFeed.</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: 
     { id: 77289038,
       id_str: '77289038',
       name: 'Polly\'s Pies',
       screen_name: 'Pollyspiescafe',
       location: 'Southern California',
       description: 'Polly\'s Pies offers excellent service, the freshest, tastiest homestyle cooking and baking - all at very reasonable prices!',
       url: 'http://t.co/CDVl5Cd0aN',
       entities: [Object],
       protected: false,
       followers_count: 1425,
       friends_count: 912,
       listed_count: 48,
       created_at: 'Fri Sep 25 19:22:11 +0000 2009',
       favourites_count: 327,
       utc_offset: -25200,
       time_zone: 'Pacific Time (US & Canada)',
       geo_enabled: true,
       verified: false,
       statuses_count: 1179,
       lang: 'en',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'BA68AE',
       profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/456584854126071808/eA4uCNEE.jpeg',
       profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/456584854126071808/eA4uCNEE.jpeg',
       profile_background_tile: true,
       profile_image_url: 'http://pbs.twimg.com/profile_images/761714490681417729/kjI3GIcB_normal.jpg',
       profile_image_url_https: 'https://pbs.twimg.com/profile_images/761714490681417729/kjI3GIcB_normal.jpg',
       profile_banner_url: 'https://pbs.twimg.com/profile_banners/77289038/1467135216',
       profile_link_color: '7FDBB6',
       profile_sidebar_border_color: 'FFFFFF',
       profile_sidebar_fill_color: 'DDFFCC',
       profile_text_color: '333333',
       profile_use_background_image: true,
       has_extended_profile: false,
       default_profile: false,
       default_profile_image: false,
       following: true,
       follow_request_sent: false,
       notifications: false },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 2,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    lang: 'en' },
  { created_at: 'Fri Jun 24 22:54:15 +0000 2016',
    id: 746476559159042000,
    id_str: '746476559159042048',
    text: 'Happy #fridaypieday! We can\'t wait to dig into this delicious fresh peach pie. #pollyspies #followifyoulovepie https://t.co/A5JFaRo5k4',
    truncated: false,
    entities: 
     { hashtags: [Object],
       symbols: [],
       user_mentions: [],
       urls: [],
       media: [Object] },
    extended_entities: { media: [Object] },
    source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: 
     { id: 77289038,
       id_str: '77289038',
       name: 'Polly\'s Pies',
       screen_name: 'Pollyspiescafe',
       location: 'Southern California',
       description: 'Polly\'s Pies offers excellent service, the freshest, tastiest homestyle cooking and baking - all at very reasonable prices!',
       url: 'http://t.co/CDVl5Cd0aN',
       entities: [Object],
       protected: false,
       followers_count: 1425,
       friends_count: 912,
       listed_count: 48,
       created_at: 'Fri Sep 25 19:22:11 +0000 2009',
       favourites_count: 327,
       utc_offset: -25200,
       time_zone: 'Pacific Time (US & Canada)',
       geo_enabled: true,
       verified: false,
       statuses_count: 1179,
       lang: 'en',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'BA68AE',
       profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/456584854126071808/eA4uCNEE.jpeg',
       profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/456584854126071808/eA4uCNEE.jpeg',
       profile_background_tile: true,
       profile_image_url: 'http://pbs.twimg.com/profile_images/761714490681417729/kjI3GIcB_normal.jpg',
       profile_image_url_https: 'https://pbs.twimg.com/profile_images/761714490681417729/kjI3GIcB_normal.jpg',
       profile_banner_url: 'https://pbs.twimg.com/profile_banners/77289038/1467135216',
       profile_link_color: '7FDBB6',
       profile_sidebar_border_color: 'FFFFFF',
       profile_sidebar_fill_color: 'DDFFCC',
       profile_text_color: '333333',
       profile_use_background_image: true,
       has_extended_profile: false,
       default_profile: false,
       default_profile_image: false,
       following: true,
       follow_request_sent: false,
       notifications: false },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    lang: 'en' },
  { created_at: 'Thu Jun 23 16:27:10 +0000 2016',
    id: 746016759182819300,
    id_str: '746016759182819328',
    text: 'RT @DanBejmuk: I think I\'m now officially hooked on #banberry @Pollyspiescafe',
    truncated: false,
    entities: 
     { hashtags: [Object],
       symbols: [],
       user_mentions: [Object],
       urls: [] },
    source: '<a href="http://momentfeed.com" rel="nofollow">MomentFeed.</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: 
     { id: 77289038,
       id_str: '77289038',
       name: 'Polly\'s Pies',
       screen_name: 'Pollyspiescafe',
       location: 'Southern California',
       description: 'Polly\'s Pies offers excellent service, the freshest, tastiest homestyle cooking and baking - all at very reasonable prices!',
       url: 'http://t.co/CDVl5Cd0aN',
       entities: [Object],
       protected: false,
       followers_count: 1425,
       friends_count: 912,
       listed_count: 48,
       created_at: 'Fri Sep 25 19:22:11 +0000 2009',
       favourites_count: 327,
       utc_offset: -25200,
       time_zone: 'Pacific Time (US & Canada)',
       geo_enabled: true,
       verified: false,
       statuses_count: 1179,
       lang: 'en',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'BA68AE',
       profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/456584854126071808/eA4uCNEE.jpeg',
       profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/456584854126071808/eA4uCNEE.jpeg',
       profile_background_tile: true,
       profile_image_url: 'http://pbs.twimg.com/profile_images/761714490681417729/kjI3GIcB_normal.jpg',
       profile_image_url_https: 'https://pbs.twimg.com/profile_images/761714490681417729/kjI3GIcB_normal.jpg',
       profile_banner_url: 'https://pbs.twimg.com/profile_banners/77289038/1467135216',
       profile_link_color: '7FDBB6',
       profile_sidebar_border_color: 'FFFFFF',
       profile_sidebar_fill_color: 'DDFFCC',
       profile_text_color: '333333',
       profile_use_background_image: true,
       has_extended_profile: false,
       default_profile: false,
       default_profile_image: false,
       following: true,
       follow_request_sent: false,
       notifications: false },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    retweeted_status: 
     { created_at: 'Thu Jun 23 01:07:35 +0000 2016',
       id: 745785340728774700,
       id_str: '745785340728774657',
       text: 'I think I\'m now officially hooked on #banberry @Pollyspiescafe',
       truncated: false,
       entities: [Object],
       source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       is_quote_status: false,
       retweet_count: 2,
       favorite_count: 2,
       favorited: false,
       retweeted: false,
       lang: 'en' },
    is_quote_status: false,
    retweet_count: 2,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: 'en' },
  { created_at: 'Wed Jun 22 00:12:10 +0000 2016',
    id: 745409006420693000,
    id_str: '745409006420692997',
    text: 'What\'s for dinner? Picture by Polly\'s Fan @caroltwang #pollyspies #followifyoulovepie https://t.co/Cc93o6vtzv',
    truncated: false,
    entities: 
     { hashtags: [Object],
       symbols: [],
       user_mentions: [],
       urls: [Object] },
    source: '<a href="http://momentfeed.com" rel="nofollow">MomentFeed.</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: 
     { id: 77289038,
       id_str: '77289038',
       name: 'Polly\'s Pies',
       screen_name: 'Pollyspiescafe',
       location: 'Southern California',
       description: 'Polly\'s Pies offers excellent service, the freshest, tastiest homestyle cooking and baking - all at very reasonable prices!',
       url: 'http://t.co/CDVl5Cd0aN',
       entities: [Object],
       protected: false,
       followers_count: 1425,
       friends_count: 912,
       listed_count: 48,
       created_at: 'Fri Sep 25 19:22:11 +0000 2009',
       favourites_count: 327,
       utc_offset: -25200,
       time_zone: 'Pacific Time (US & Canada)',
       geo_enabled: true,
       verified: false,
       statuses_count: 1179,
       lang: 'en',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'BA68AE',
       profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/456584854126071808/eA4uCNEE.jpeg',
       profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/456584854126071808/eA4uCNEE.jpeg',
       profile_background_tile: true,
       profile_image_url: 'http://pbs.twimg.com/profile_images/761714490681417729/kjI3GIcB_normal.jpg',
       profile_image_url_https: 'https://pbs.twimg.com/profile_images/761714490681417729/kjI3GIcB_normal.jpg',
       profile_banner_url: 'https://pbs.twimg.com/profile_banners/77289038/1467135216',
       profile_link_color: '7FDBB6',
       profile_sidebar_border_color: 'FFFFFF',
       profile_sidebar_fill_color: 'DDFFCC',
       profile_text_color: '333333',
       profile_use_background_image: true,
       has_extended_profile: false,
       default_profile: false,
       default_profile_image: false,
       following: true,
       follow_request_sent: false,
       notifications: false },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    lang: 'en' },
  { created_at: 'Mon Jun 20 23:54:10 +0000 2016',
    id: 745042087880495100,
    id_str: '745042087880495105',
    text: 'Polly\'s Fan @jackie.ruesga knows how to beat the heat: our fresh Strawberry Lemonade! (Make that two!) https://t.co/zMvYJOnD6D',
    truncated: false,
    entities: 
     { hashtags: [],
       symbols: [],
       user_mentions: [Object],
       urls: [Object] },
    source: '<a href="http://momentfeed.com" rel="nofollow">MomentFeed.</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: 
     { id: 77289038,
       id_str: '77289038',
       name: 'Polly\'s Pies',
       screen_name: 'Pollyspiescafe',
       location: 'Southern California',
       description: 'Polly\'s Pies offers excellent service, the freshest, tastiest homestyle cooking and baking - all at very reasonable prices!',
       url: 'http://t.co/CDVl5Cd0aN',
       entities: [Object],
       protected: false,
       followers_count: 1425,
       friends_count: 912,
       listed_count: 48,
       created_at: 'Fri Sep 25 19:22:11 +0000 2009',
       favourites_count: 327,
       utc_offset: -25200,
       time_zone: 'Pacific Time (US & Canada)',
       geo_enabled: true,
       verified: false,
       statuses_count: 1179,
       lang: 'en',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'BA68AE',
       profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/456584854126071808/eA4uCNEE.jpeg',
       profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/456584854126071808/eA4uCNEE.jpeg',
       profile_background_tile: true,
       profile_image_url: 'http://pbs.twimg.com/profile_images/761714490681417729/kjI3GIcB_normal.jpg',
       profile_image_url_https: 'https://pbs.twimg.com/profile_images/761714490681417729/kjI3GIcB_normal.jpg',
       profile_banner_url: 'https://pbs.twimg.com/profile_banners/77289038/1467135216',
       profile_link_color: '7FDBB6',
       profile_sidebar_border_color: 'FFFFFF',
       profile_sidebar_fill_color: 'DDFFCC',
       profile_text_color: '333333',
       profile_use_background_image: true,
       has_extended_profile: false,
       default_profile: false,
       default_profile_image: false,
       following: true,
       follow_request_sent: false,
       notifications: false },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    lang: 'en' },
  { created_at: 'Fri Jun 17 23:41:10 +0000 2016',
    id: 743951651745079300,
    id_str: '743951651745079296',
    text: 'Our featured pie for #fridaypieday is our Strawberry Rhubarb! Here until June 27th #pollyspies #followifyoulovepie https://t.co/pRXJqTkomB',
    truncated: false,
    entities: 
     { hashtags: [Object],
       symbols: [],
       user_mentions: [],
       urls: [Object] },
    source: '<a href="http://momentfeed.com" rel="nofollow">MomentFeed.</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: 
     { id: 77289038,
       id_str: '77289038',
       name: 'Polly\'s Pies',
       screen_name: 'Pollyspiescafe',
       location: 'Southern California',
       description: 'Polly\'s Pies offers excellent service, the freshest, tastiest homestyle cooking and baking - all at very reasonable prices!',
       url: 'http://t.co/CDVl5Cd0aN',
       entities: [Object],
       protected: false,
       followers_count: 1425,
       friends_count: 912,
       listed_count: 48,
       created_at: 'Fri Sep 25 19:22:11 +0000 2009',
       favourites_count: 327,
       utc_offset: -25200,
       time_zone: 'Pacific Time (US & Canada)',
       geo_enabled: true,
       verified: false,
       statuses_count: 1179,
       lang: 'en',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'BA68AE',
       profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/456584854126071808/eA4uCNEE.jpeg',
       profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/456584854126071808/eA4uCNEE.jpeg',
       profile_background_tile: true,
       profile_image_url: 'http://pbs.twimg.com/profile_images/761714490681417729/kjI3GIcB_normal.jpg',
       profile_image_url_https: 'https://pbs.twimg.com/profile_images/761714490681417729/kjI3GIcB_normal.jpg',
       profile_banner_url: 'https://pbs.twimg.com/profile_banners/77289038/1467135216',
       profile_link_color: '7FDBB6',
       profile_sidebar_border_color: 'FFFFFF',
       profile_sidebar_fill_color: 'DDFFCC',
       profile_text_color: '333333',
       profile_use_background_image: true,
       has_extended_profile: false,
       default_profile: false,
       default_profile_image: false,
       following: true,
       follow_request_sent: false,
       notifications: false },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 1,
    favorite_count: 1,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    lang: 'en' },
  { created_at: 'Fri Jun 17 00:20:10 +0000 2016',
    id: 743599078324375600,
    id_str: '743599078324375553',
    text: 'Photo by Polly\'s Fan @alodevico  https://t.co/QhNzmRyDbk',
    truncated: false,
    entities: 
     { hashtags: [],
       symbols: [],
       user_mentions: [Object],
       urls: [Object] },
    source: '<a href="http://momentfeed.com" rel="nofollow">MomentFeed.</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: 
     { id: 77289038,
       id_str: '77289038',
       name: 'Polly\'s Pies',
       screen_name: 'Pollyspiescafe',
       location: 'Southern California',
       description: 'Polly\'s Pies offers excellent service, the freshest, tastiest homestyle cooking and baking - all at very reasonable prices!',
       url: 'http://t.co/CDVl5Cd0aN',
       entities: [Object],
       protected: false,
       followers_count: 1425,
       friends_count: 912,
       listed_count: 48,
       created_at: 'Fri Sep 25 19:22:11 +0000 2009',
       favourites_count: 327,
       utc_offset: -25200,
       time_zone: 'Pacific Time (US & Canada)',
       geo_enabled: true,
       verified: false,
       statuses_count: 1179,
       lang: 'en',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'BA68AE',
       profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/456584854126071808/eA4uCNEE.jpeg',
       profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/456584854126071808/eA4uCNEE.jpeg',
       profile_background_tile: true,
       profile_image_url: 'http://pbs.twimg.com/profile_images/761714490681417729/kjI3GIcB_normal.jpg',
       profile_image_url_https: 'https://pbs.twimg.com/profile_images/761714490681417729/kjI3GIcB_normal.jpg',
       profile_banner_url: 'https://pbs.twimg.com/profile_banners/77289038/1467135216',
       profile_link_color: '7FDBB6',
       profile_sidebar_border_color: 'FFFFFF',
       profile_sidebar_fill_color: 'DDFFCC',
       profile_text_color: '333333',
       profile_use_background_image: true,
       has_extended_profile: false,
       default_profile: false,
       default_profile_image: false,
       following: true,
       follow_request_sent: false,
       notifications: false },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    lang: 'en' } ]
}